### ISSUE TITLE
Compile an example code for T-Beam v1.2

### ISSUE THREAD

**Issue by sirfonzie** [Xinyuan-LilyGO/LilyGo-LoRa-Series#201]
I am having issues even to compile the example code in Arduino as when I execute the code, it goes into a infinite watchdog reset loop. 
I followed the setup for ESP32 Dev Module. I cant figure out where I am making a mistake.

**Comment by lewisxhe** [comment]
Arduino IDE board settings, running examples, tell me respectively

**Comment by sirfonzie** [comment]
![image](https://github.com/user-attachments/assets/d00c4fed-81b5-4fe8-8412-f88f936d4b60)

I am using the T-Beam V1.2 (SX1262), thus I uncommented (in utilities.h file):
#define T3_S3_V1_2_SX1262

Running this example: https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/examples/RadioLibExamples/Transmit_Interrupt

When compiled and uploaded, I get this error:

-----------------------------------
ets Jul 29 2019 12:21:46

rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4832
load:0x40078000,len:16460
load:0x40080400,len:4
load:0x40080404,len:3504
entry 0x400805cc
setupBoards
-----------------------------------
Reset reason: In case of deep sleep, reset was not caused by exit from deep sleep
PSRAM is enable! PSRAM: 4.00MB
Flash:4 MB
Flash speed:80 M
Model:ESP32-D0WDQ6-V3
Chip Revision:45
Freq:240 MHZ
SDK Ver:v5.1.4-828-g33fbade6b8-dirty
DATE:Sep 27 2024
TIME:17:30:07
EFUSE MAC: 606DF6E0F908
-----------------------------------

**Comment by lewisxhe** [comment]
Try lowering the Arduino ESP32 version to 2.0.14

![image](https://github.com/user-attachments/assets/a29bd02d-e7d2-45c9-8624-7d614556b627)

**Comment by moshe-braner** [comment]
On the other hand need at least 2.0.15 to get the fixes for Serial output via USB if compiling for the ESP32-S3.  So cannot use the same environment to compile for both devices?  What is the bug in 2.0.15+ regarding the T-Beam?

**Comment by lewisxhe** [comment]
It should work with 2.0.15, but I don't have the board now, so I can't test it. I will test it later. Theoretically, it can also run with 3.0 or above, but if there is a problem, downgrade first to see if the same problem occurs.

**Comment by sem-feldoe** [comment]
Hello i got mine today ( 866MHz )
Used #define T3_S3_V1_2_SX1276 and got the same behavior:

rst:0x8 (TG1WDT_SYS_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4832
load:0x40078000,len:16460
load:0x40080400,len:4
load:0x40080404,len:3504
entry 0x400805cc
setupBoards
-----------------------------------
Reset reason: In case of deep sleep, reset was not caused by exit from deep sleep
PSRAM is disable!
Flash:4 MB
Flash speed:80 M
Model:ESP32-D0WDQ6-V3
Chip Revision:45
Freq:240 MHZ
SDK Ver:v5.1.4-828-g33fbade6b8-dirty
DATE:Oct 19 2024
TIME:13:30:10
EFUSE MAC: 64FB726CDDA0

I downgraded but then it fails to compile.
@sirfonzie Did you find a way to make it work?
Thanks

**Comment by lewisxhe** [comment]
Can't compile? Please take a screenshot or provide a log of the compilation error

**Comment by lewisxhe** [comment]
![PixPin_2024-10-21_11-21-51](https://github.com/user-attachments/assets/8184c0b4-93b1-4492-93a2-aa9ec2321383)
![esp](https://github.com/user-attachments/assets/0899f97e-7763-47a3-b88a-0e18f66c67ac)
![PixPin_2024-10-21_11-21-18](https://github.com/user-attachments/assets/e3532581-7f7d-4f4b-80df-972cbf941331)
Just tested the latest 3.0.5 ArduinoLoRa and RadioLib can work properly

**Comment by sem-feldoe** [comment]
Hello @lewisxhe ,
I did a lot of tests, i can make it working if i use
#define T3_V1_3_SX1276
and i commented "beginWiFi();" that makes the board crash from setupBoards().
It should be nice to have a table for matching label on board and the define to use in utilities.h
i have a T-BEAM-AXP2101-V1.2, it's quite hard to guess that we need to use T3_V1_3_SX1276 to make it works!
Now that i can make a simple sketch works, i will try more things,
thanks lewisxhe!

**Comment by lewisxhe** [comment]
beginWiFi() requires a lot of power. If you add a battery, it won't crash. If you don't need it, you can remove it first.

**Comment by sem-feldoe** [comment]
I tried a more powerfull usb port and i can use Wifi and connect to a router etc... It's nice! thanks.
