### ISSUE TITLE
can't get OTTA example to work with T3_V1.6

### ISSUE THREAD

**Issue by markdahmke** [Xinyuan-LilyGO/LilyGo-LoRa-Series#103]
I'm trying to compile the example for TTN but am getting errors, including:
loramac.cpp:184:50: error: 'DR_SF12' was not declared in this scope
lmic.h:680:50: note: in definition of macro 'DR_RANGE_MAP'
loramac.cpp:184:69: error: 'BAND_CENTI' was not declared in this scope

I've installed the MCCI Arduino Lorawan Library.  Suggestions would be appreciated.
Thanks

**Comment by afialexandre** [comment]
Hello, I've had the same problem without being able to solve it. Have you found a solution
Thanks.
